/* Japanese glosses for the most commonly formed words.
 * 見つけた単語の意味をその場で表示するための対訳データ。
 * ここに無い単語は意味なしで表示される（辞書判定には影響しない）。
 */
window.USPEAK_MEANINGS = {
  ace: 'エース', act: '行動する', add: '加える', age: '年齢', aid: '助け', aim: '狙う',
  air: '空気', ant: 'アリ', any: 'どれか', ape: '類人猿', arm: '腕', art: '芸術',
  ask: '尋ねる', ate: '食べた', axe: 'おの', bad: '悪い', bag: 'かばん', bar: '棒',
  bat: 'コウモリ／バット', bay: '湾', bed: 'ベッド', bee: 'ハチ', beg: '頼む', bet: '賭ける',
  big: '大きい', bit: '少し', bow: 'おじぎ', box: '箱', boy: '男の子', bug: '虫',
  bus: 'バス', buy: '買う', cab: 'タクシー', can: 'できる', cap: '帽子', car: '車',
  cat: 'ねこ', cow: '牛', cry: '泣く', cub: '子ども（動物）', cup: 'コップ', cut: '切る',
  dad: 'お父さん', day: '日', den: '巣穴', dew: '露', die: '死ぬ', dig: '掘る',
  dog: 'いぬ', dot: '点', dry: '乾いた', due: '期限の', dye: '染める', ear: '耳',
  eat: '食べる', egg: 'たまご', elf: '妖精', end: '終わり', eye: '目', fan: '扇風機／ファン',
  far: '遠い', fat: '太った', fee: '料金', few: '少しの', fig: 'いちじく', fit: '合う',
  fix: '直す', fly: '飛ぶ', fog: '霧', for: '〜のために', fox: 'きつね', fry: '揚げる',
  fun: '楽しい', fur: '毛皮', gas: '気体', gem: '宝石', get: '手に入れる', gum: 'ガム',
  gun: '銃', guy: '男', gym: '体育館', ham: 'ハム', hat: 'ぼうし', hen: 'めんどり',
  her: '彼女の', hit: '打つ', hop: '跳ぶ', hot: '熱い', how: 'どのように', hug: '抱きしめる',
  hut: '小屋', ice: '氷', ill: '病気の', ink: 'インク', inn: '宿', ion: 'イオン',
  jam: 'ジャム', jar: 'びん', jet: 'ジェット機', job: '仕事', jog: 'ジョギングする', joy: '喜び',
  key: 'かぎ', kid: '子ども', kit: '道具一式', lab: '実験室', law: '法律', lay: '置く',
  leg: '足', let: '〜させる', lid: 'ふた', lie: 'うそ／横たわる', lip: 'くちびる', log: '丸太',
  lot: 'たくさん', low: '低い', mad: '怒った', man: '男の人', map: '地図', mat: 'マット',
  mix: '混ぜる', mom: 'お母さん', mud: '泥', mug: 'マグカップ', nap: '昼寝', net: '網',
  new: '新しい', nod: 'うなずく', not: '〜でない', now: '今', nut: '木の実', oak: 'かしの木',
  oil: '油', old: '古い', one: '１つ', our: '私たちの', out: '外へ', owl: 'ふくろう',
  own: '自分の', pan: 'フライパン', pay: '払う', pea: 'えんどう豆', pen: 'ペン', pet: 'ペット',
  pie: 'パイ', pig: 'ぶた', pin: 'ピン', pot: 'なべ', pup: '子いぬ', put: '置く',
  ram: '雄羊', rat: 'ねずみ', raw: '生の', red: '赤', rib: 'あばら骨', rid: '取り除く',
  rob: '奪う', row: '列', rub: 'こする', rug: 'じゅうたん', run: '走る', sad: '悲しい',
  sat: '座った', saw: '見た／のこぎり', say: '言う', sea: '海', see: '見る', set: '置く',
  she: '彼女', shy: '恥ずかしがりの', sit: '座る', six: '６', ski: 'スキー', sky: '空',
  son: '息子', spy: 'スパイ', sun: '太陽', tag: '札', tan: '日焼け', tax: '税金',
  tea: 'お茶', ten: '１０', the: 'その', tie: 'ネクタイ／結ぶ', tip: '先端／コツ', toe: 'つま先',
  ton: 'トン', top: '一番上', toy: 'おもちゃ', try: 'やってみる', two: '２', use: '使う',
  van: 'バン', war: '戦争', was: '〜だった', way: '道', web: 'ウェブ', wet: 'ぬれた',
  who: 'だれ', why: 'なぜ', win: '勝つ', yes: 'はい', yet: 'まだ', you: 'あなた',
  zoo: '動物園',

  able: 'できる', baby: '赤ちゃん', back: '背中／戻る', ball: 'ボール', band: 'バンド',
  bank: '銀行', bath: 'ふろ', bean: '豆', bear: 'くま', beat: '打つ', beef: '牛肉',
  bell: 'ベル', bird: 'とり', bite: 'かむ', blue: '青', boat: 'ボート', body: '体',
  bone: '骨', book: '本', boot: 'ブーツ', both: '両方', bowl: 'ボウル', cage: 'かご',
  cake: 'ケーキ', call: '呼ぶ', calm: '静かな', camp: 'キャンプ', card: 'カード', care: '世話',
  cash: '現金', cave: '洞くつ', city: '都市', clam: '貝', clay: '粘土', club: 'クラブ',
  coal: '石炭', coat: 'コート', coin: 'コイン', cold: '寒い', come: '来る', cook: '料理する',
  cool: '涼しい', copy: '写す', corn: 'とうもろこし', crab: 'かに', crow: 'カラス', cute: 'かわいい',
  dark: '暗い', desk: '机', dish: '皿', door: 'ドア', down: '下へ', draw: '描く',
  dream: '夢', drop: '落とす', duck: 'あひる', each: 'それぞれ', east: '東', easy: '簡単な',
  face: '顔', fact: '事実', fall: '落ちる', farm: '農場', fast: '速い', feel: '感じる',
  find: '見つける', fire: '火', fish: '魚', five: '５', flag: '旗', food: '食べ物',
  foot: '足', four: '４', free: '自由な', frog: 'カエル', from: '〜から', game: 'ゲーム',
  gate: '門', gift: 'おくりもの', girl: '女の子', give: '与える', glad: 'うれしい', goat: 'やぎ',
  gold: '金', good: '良い', hair: '髪', half: '半分', hand: '手', hard: 'かたい／難しい',
  have: '持つ', head: '頭', hear: '聞く', help: '助ける', hero: '英雄', hide: '隠す',
  high: '高い', hill: '丘', home: '家', hope: '希望', horn: 'つの', hour: '時間',
  huge: '巨大な', idea: '考え', jump: '跳ぶ', keep: '保つ', kind: '親切な', king: '王',
  kiss: 'キス', know: '知る', lake: '湖', lamb: '子羊', lamp: 'ランプ', land: '土地',
  late: '遅い', leaf: '葉', life: '命', like: '好き', line: '線', lion: 'ライオン',
  long: '長い', look: '見る', love: '愛', luck: '運', mail: '郵便', many: '多くの',
  meat: '肉', milk: 'ぎゅうにゅう', mind: '心', moon: '月', more: 'もっと', move: '動く',
  name: '名前', near: '近い', neck: '首', need: '必要とする', nest: '巣', nice: 'すてきな',
  nine: '９', nose: '鼻', note: 'メモ', okay: 'だいじょうぶ', open: '開ける', oven: 'オーブン',
  pain: '痛み', pair: 'ペア', park: '公園', part: '部分', path: '小道', pear: '洋なし',
  pink: 'ピンク', plan: '計画', play: '遊ぶ', pool: 'プール', poor: '貧しい', pork: 'ぶた肉',
  rain: '雨', read: '読む', rice: 'ごはん', ride: '乗る', ring: '指輪', road: '道路',
  rock: '岩', roof: '屋根', room: '部屋', root: '根', rose: 'ばら', safe: '安全な',
  sail: '帆走する', salt: '塩', same: '同じ', sand: '砂', seat: '席', seed: '種',
  ship: '船', shoe: 'くつ', shop: '店', show: '見せる', sing: '歌う', sink: '沈む',
  skin: '皮ふ', sky: '空', slow: '遅い', snow: '雪', soap: 'せっけん', sofa: 'ソファ',
  soft: 'やわらかい', song: '歌', soup: 'スープ', star: '星', stay: 'とどまる', step: '歩み',
  stop: '止まる', swim: '泳ぐ', tail: 'しっぽ', take: '取る', talk: '話す', tall: '背の高い',
  team: 'チーム', tear: '涙', tell: '伝える', tent: 'テント', test: 'テスト', text: '文章',
  than: '〜より', that: 'あれ', them: '彼らを', then: 'それから', they: '彼ら', thin: '細い',
  this: 'これ', time: '時間', tiny: '小さな', tire: 'タイヤ', toad: 'ヒキガエル', town: '町',
  tree: '木', trip: '旅行', true: '本当の', turn: '回る', ugly: 'みにくい', view: '景色',
  wait: '待つ', wake: '起きる', walk: '歩く', wall: 'かべ', want: '欲しい', warm: '暖かい',
  wash: '洗う', wave: '波', weak: '弱い', wear: '着る', week: '週', well: 'よく',
  west: '西', what: '何', when: 'いつ', wide: '広い', wild: '野生の', wind: '風',
  wing: 'つばさ', wish: '願う', with: '〜と一緒に', wolf: 'おおかみ', wood: '木材', word: '単語',
  work: '働く', worm: 'ミミズ', yard: '庭', year: '年', your: 'あなたの', zero: '０',

  about: '〜について', above: '上に', angry: '怒った', apple: 'りんご', beach: '浜辺',
  bread: 'パン', brave: '勇敢な', bring: '持ってくる', brown: '茶色', candy: 'キャンディ',
  chair: 'いす', chalk: 'チョーク', cheap: '安い', check: '調べる', chess: 'チェス',
  child: '子ども', clean: 'きれいな', clear: '明らかな', climb: '登る', clock: '時計',
  cloud: '雲', color: '色', crazy: 'クレイジーな', cream: 'クリーム', dance: '踊る',
  dream: '夢', dress: 'ドレス', drink: '飲む', drive: '運転する', eagle: 'ワシ',
  early: '早い', earth: '地球', eight: '８', empty: '空の', enjoy: '楽しむ',
  every: 'すべての', field: '野原', fight: '戦う', first: '最初の', floor: '床',
  flour: '小麦粉', flower: '花', fruit: 'くだもの', funny: 'おもしろい', ghost: 'おばけ',
  giant: '巨人', glass: 'ガラス', grape: 'ぶどう', grass: '草', great: 'すばらしい',
  green: '緑', happy: '幸せな', heart: '心臓', heavy: '重い', horse: '馬',
  house: '家', juice: 'ジュース', knife: 'ナイフ', large: '大きい', laugh: '笑う',
  learn: '学ぶ', lemon: 'レモン', light: '光', lunch: '昼食', money: 'お金',
  month: '月', mouse: 'ねずみ', mouth: '口', music: '音楽', night: '夜',
  ocean: '海', panda: 'パンダ', paper: '紙', party: 'パーティー', peace: '平和',
  peach: 'もも', pizza: 'ピザ', place: '場所', plant: '植物', quiet: '静かな',
  quick: '速い', river: '川', round: '丸い', salad: 'サラダ', school: '学校',
  sheep: 'ひつじ', shirt: 'シャツ', short: '短い', sleep: 'ねむる', small: '小さい',
  smile: 'ほほえむ', snake: 'へび', space: '宇宙', spoon: 'スプーン', sport: 'スポーツ',
  stone: '石', storm: 'あらし', story: '物語', study: '勉強する', sugar: '砂糖',
  sweet: '甘い', table: 'テーブル', teach: '教える', thank: '感謝する', think: '考える',
  three: '３', tiger: 'とら', today: '今日', train: '電車', water: '水',
  whale: 'くじら', wheel: '車輪', white: '白', world: '世界', write: '書く',
  young: '若い', zebra: 'シマウマ',

  animal: '動物', autumn: '秋', banana: 'バナナ', basket: 'かご', bottle: 'びん',
  bridge: '橋', butter: 'バター', camera: 'カメラ', candle: 'ろうそく', castle: '城',
  cheese: 'チーズ', circle: '円', coffee: 'コーヒー', cookie: 'クッキー', dinner: '夕食',
  doctor: '医者', family: '家族', father: '父', flower: '花', forest: '森',
  friend: '友だち', future: '未来', garden: '庭', ground: '地面', guitar: 'ギター',
  island: '島', jacket: '上着', jungle: 'ジャングル', letter: '手紙', listen: '聞く',
  market: '市場', middle: '真ん中', minute: '分', monkey: 'さる', mother: '母',
  number: '数', orange: 'オレンジ', parent: '親', pencil: 'えんぴつ', people: '人々',
  pocket: 'ポケット', potato: 'じゃがいも', rabbit: 'うさぎ', river: '川', school: '学校',
  season: '季節', silver: '銀', simple: '簡単な', singer: '歌手', sister: '姉妹',
  spring: '春', square: '四角', street: '通り', strong: '強い', summer: '夏',
  sunny: '晴れた', supper: '夕食', teacher: '先生', ticket: 'チケット', tomato: 'トマト',
  travel: '旅行する', turtle: 'かめ', window: '窓', winter: '冬', yellow: '黄色',

  animals: '動物たち', another: 'もう一つの', because: 'なぜなら', between: '〜の間',
  brother: '兄弟', chicken: 'とり肉／にわとり', country: '国', dolphin: 'イルカ',
  evening: '夕方', example: '例', holiday: '休日', kitchen: '台所', library: '図書館',
  morning: '朝', nothing: '何も〜ない', picture: '絵', present: 'プレゼント',
  problem: '問題', science: '科学', station: '駅', student: '生徒', subject: '教科',
  weather: '天気', because: 'なぜなら',

  birthday: '誕生日', children: '子どもたち', computer: 'コンピュータ', elephant: 'ぞう',
  favorite: 'お気に入りの', hospital: '病院', mountain: '山', sandwich: 'サンドイッチ',
  swimming: '水泳', together: '一緒に', tomorrow: '明日', vacation: '休暇',
  question: '質問', baseball: '野球', football: 'サッカー', umbrella: 'かさ'
};
